homeassistant:
  legacy_templates: false
  allowlist_external_dirs:
    - "/config/"
  #latitude: !secret latitude
  #longitude: !secret longitude
  #elevation: 311
  # Customization file
  customize: !include customize.yaml

readme:

folder_watcher:
  - folder: /config

zoneminder:
  - host: !secret ZM_HOST
    ssl: false
    username: !secret ZM_USERNAME
    password: !secret ZM_PASSWORD

camera:
  - platform: zoneminder

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named themes/

#Lovelace
lovelace:
  mode: storage
  #Add yaml dashboards
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Lovelace-tablet-1
      icon: mdi:tablet
      show_in_sidebar: true
      filename: lovelace.yaml
    lovelace-tablet:
      mode: yaml
      title: Lovelace-tablet
      icon: mdi:tablet
      show_in_sidebar: true
      filename: lovelace-tablet.yaml

    lovelace-phone:
      mode: yaml
      title: Lovelace-phone
      icon: mdi:cellphone-android
      show_in_sidebar: true
      filename: lovelace-phone.yaml
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
#  base_url:

# Discover some devices automatically
discovery:
hassio:
# Sensors
sensor: !include sensors.yaml

#RFlink
rflink:
  host: 192.168.15.253
  port: 6000

# Text to speech
tts:
  - platform: google_translate

light: !include lights.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#Media Players
media_player: !include media_players.yaml

#Binary sensors
binary_sensor: !include binary_sensors.yaml

#Speedtest
speedtestdotnet:
  scan_interval:
    minutes: 5

#Digital Ocean
digital_ocean:
  access_token: !secret digital_ocean_api

#Influxdb
influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

#Google Calendar
google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

#WebosTV
webostv:
  - host: 192.168.15.201
    name: Vardagrsum TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: 3C:CD:93:ED:7C:4F
    customize:
      sources:
        - LiveTV
        - Netflix
        - Onkyo
        - YouTube

#Trakt
#trakt:
#  client_id: !secret trakt_id
#  client_secret: !secret trakt_secret

#Spotify to chromecast
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

#Spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

#Debug
logger:
  default: info
  logs:
    # Detected I/O
    homeassistant.util.async: fatal
    homeassistant.util.async_: fatal
  #logs:
  #rflink: debug
  #homeassistant.components.rflink: debug
#switch: !include switch.yaml

### Office 365 ###
o365:
  client_secret: !secret o365_klientsecret
  client_id: !secret o365_klientid
  alt_auth_flow: true
  email_sensor:
    - name: inbox
      max_items: 2
      is_unread: True
  query_sensors:
    - name: "HA Notifications"
      folder: "Inbox/Test_Inbox"
      from: !secret o365_mail
      subject_contains: "Notifcation from home assistant"
      has_attachment: True
      max_items: 2
      is_unread: True

#Mousetrapper counter
counter:
  mousetrappedhouse:
    initial: 4
    step: 1
    icon: twemoji:mouse
  mousetrappedtrain:
    initial: 0
    step: 1
    icon: twemoji:mouse

#Proximity
proximity:
  home:
    devices:
      - device_tracker.oneplus_a6003
    tolerance: 50
    unit_of_measurement: km
  work:
    zone: jobb
    devices:
      - device_tracker.oneplus_a6003
    tolerance: 50
    unit_of_measurement: km

utility_meter:
  samuel_steps:
    source: sensor.samuels_oneplus_steps_sensor
    cycle: daily

#browser_mods
browser_mod:
  prefix: "browser_"
  devices:
    3803775c_e70cb959:
      name: kitchen_ipad
      camera: true

#Alarm for homekit-infused
alarm_control_panel:
  - platform: manual
    code: !secret alarm_code

#Emulated hue
emulated_hue:
  listen_port: 80
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
