- platform: rflink
  automatic_add: true
  devices:
    newkaku_01718f56_10:
      name: Ljusstake Vardagsrum
      type: switchable
    newkaku_0171856_e:
      name: TV-room LED slinga
      type: dimmable
    newkaku_0171856_f:
      name: Lampa 2
      type: switchable
    newkaku_01318b56_f:
      name: Dining room wall light
      type: switchable
    newkaku_01318b56_10:
      name: Sovrum fönster
      type: switchable
    newkaku_01318b56_e:
      name: Office wall lights
      type: switchable
- platform: group
  name: Upstairs lights
  entities:
    - light.color_temperature_light_3
    - light.office_wall_lights
    - light.tv_room_led_slinga
- platform: group
  name: Downstairs lights
  entities:
    - light.color_temperature_light_4
    - light.color_temperature_light_5
    - light.dimmable_light_8
    - light.dining_room_wall_light
- platform: group
  name: Living room lights
  entities:
    - light.color_temperature_light_4
    - light.color_temperature_light_5
- platform: group
  name: Kitchen room lights
  entities:
    - light.dimmable_light_8
    - light.dining_room_wall_light

- platform: group
  name: Christmas lights
  entities:
    - light.ljusstake_vardagsrum
    - light.sovrum_fonster
    - light.ljusstake_kok
    - light.ljusstake_taghus

    ### Switches ###
- platform: switch
  name: Ljusstake tåghus
  entity_id: switch.on_off_plug_in_unit_6

- platform: switch
  name: Ljusstake kök
  entity_id: switch.on_off_plug_in_unit_7
