##########################################################################
#                                                                        #
#                              * SETTINGS *                              #
#                                                                        #
##########################################################################

preload_cards: [map, iframe, markdown]
preload_rows: [input-select-entity]

anchors:
  ⚓₁: &title
    entity: sensor.placeholder
    tap_action:
      action: none
    hold_action:
      action: none
    type: state-label
  ⚓₂: &title-style
    color: "#bcbebf"
    font-family: SF Text
    font-size: 2.4vw
    font-weight: 500
    max-width: 1px
    cursor: default

button_card_templates: !include button_card_templates.yaml

views:
  - title: Hem
    path: hem
    icon: "mdi:home"
    theme: tablet
    cards:
      - type: custom:layout-card
        layout: vertical
        column_num: 2
        cards:
          #################################################
          #                                               #
          #                    Samuel                    #
          #                                               #
          #################################################

          - type: "custom:person-card"
            person: person.samuel_sjobergsson
            phone_battery_sensor: sensor.oneplus_a6003_battery_level
            border_color: white
            entities:
              - entity: sensor.person_samuel_closest
            hold_action: !include popup/hemma_samuel.yaml
            tap_action: !include popup/hemma_samuel.yaml

          #################################################
          #                                               #
          #                     SANJA                     #
          #                                               #
          #################################################

          #- type: custom:button-card
          #entity: person.sanja
          #triggers_update: ["person.sanja", "sensor.time"]
          #style:
          #top: 23.9%
          #left: 76.2%
          #width: 47.7%
          #tap_action: !include popup/hemma_sanja.yaml
          #hold_action: !include popup/hemma_sanja.yaml
          #template: person

          - break

          - type: markdown
            content: >
              <span>{{ states('sensor.time') }}</span>


              <font color='#6a7377'><b>{{ states('sensor.sidebar_day') }}</b><br>
              <b>{{ states('sensor.sidebar_date') }}</b> </font><br> 


              <b>{{ states('sensor.sidebar_greeting') }}</b>


              <b>{{ states('sensor.sidebar_active') }}</b>


              <b>{{ states('sensor.sidebar_weather') }}</b>


              <b>{{states('sensor.garbage_disposal') }}</b>


              <b>{{states('sensor.sidebar_dagenscitat')}}</b>

              {% if is_state('binary_sensor.google', 'off') %}
              {{'\u26A0\uFE0F'}} Kontrollera internetåtkomst{% endif %}
              </font>

      - type: "custom:swipe-card"
        cards:
          - type: picture-elements
            image: >-
              data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'
              viewBox='0 0 50 50' /%3E
            elements:
              - type: "custom:button-card"
                entity: media_player.master_bedroom_speaker
                name: Master Bedroom Speaker
                custom_fields:
                  icon: '<ha-icon icon="mdi:spotify"></ha-icon>'
                style:
                  top: 23.9%
                  left: 23.8%
                  width: 47.7%
                template: media
              - type: "custom:button-card"
                entity: media_player.spotify_samuel_sjobergsson
                name: Spotify Samuel Sjöbergsson
                custom_fields:
                  icon: |
                    <ha-icon icon="mdi:spotify"></ha-icon>
                style:
                  top: 23.9%
                  left: 76.2%
                  width: 47.7%
                template: media
              - type: "custom:button-card"
                entity: media_player.tv
                name: TV
                custom_fields:
                  icon: |
                    <ha-icon icon="mdi:television"></ha-icon>
                style:
                  top: 76.2%
                  left: 23.8%
                  width: 47.7%
                template: media

              ##########################################################################
              #                                                                        #
              #                             * VARDAGSRUM *                             #
              #                                                                        #
              ##########################################################################

          - type: grid
            columns: 2
            title: Vardagsrum
            cards:
              #################################################
              #                                               #
              #                   BELYSNING                   #
              #                                               #
              #################################################

              - type: custom:button-card
                entity: light.living_room_lights
                name: Fönsterlampor
                style:
                  width: 47.7%
                custom_fields:
                  icon_lamp: &icon_lamp >
                    [[[ const state = entity.state === 'on' ? 'animate' : null; 
                    return `<svg viewBox="0 0 50 50"><style>@keyframes animate{0%{transform: scale(0.85);}20%{transform: scale(1.1);}40%{transform: scale(0.95);}60%{transform: scale(1.03);}80%{transform: scale(0.97);}}.animate{animation: animate 0.8s; transform-origin: center;}</style>
                    <path fill="#9da0a2" d="M26.5 21.8l3.8-6.1H19.7l3.8 6.1c-5 .7-6.3 5.8-5.7 10.2.7 5.1 3.2 10.1 5.7 14.4H19v2.5h11.8v-2.5h-4.5C29 42 31.4 37 32.1 32c.6-4.4-.6-9.4-5.6-10.2zm3.1 9.1c-.3 4.3-2.3 8.7-4.4 12.4l-.2.1v.1-.1c-1.8-3-3.3-6.4-4.1-9.7-.7-3.1-1-7.2 2.7-8.4 1.4-.5 3.1-.1 4.2.8 1.6 1 1.8 3 1.8 4.8z"/>
                    <path class="${state}" fill="var(--button-card-light-color-no-temperature)" d="M38.1 20L35.7 3.8c-.3-1.9-.4-1.7-.6-2-.9-.6-2.3-.7-2.3-.7H17.4s-1.4 0-2.3.7c-.2.3-.3.1-.6 2C14 5.7 11.9 20 11.9 20s5.8.3 13.4.3h0c7.3 0 12.8-.3 12.8-.3z"/> </svg>`;]]]
                styles: &icon_lamp_styles
                  custom_fields:
                    icon_lamp:
                      [top: 11%, left: 4.5%, width: 10.05vw, position: absolute]
                template: light

              - type: conditional
                conditions:
                  - entity: input_boolean.julbelysning
                    state: "on"
                card:
                  type: custom:button-card
                  entity: light.ljusstake_vardagsrum
                  name: Adventsljusstake
                  style:
                    width: 47.7%
                  custom_fields:
                    icon_lamp: *icon_lamp
                  styles: *icon_lamp_styles
                  template: light

              - type: custom:button-card
                entity: sensor.tunex_b301_temp
                name: Vardagsrum
                style:
                  width: 47.7%
                custom_fields:
                  icon_lamp: >
                    <ha-icon icon="mdi:thermometer"></ha-icon>
                styles: *icon_lamp_styles
                template: base
                tap-action:
                  action: more-info

          ##########################################################################
          #                                                                        #
          #                             * KÖK *                                    #
          #                                                                        #
          ##########################################################################
          - type: grid
            columns: 2
            title: Kök
            cards:
              #################################################
              #                                               #
              #                   BELYSNING                   #
              #                                               #
              #################################################

              - type: custom:button-card
                entity: light.dimmable_light_8
                name: Köksfönster
                style:
                  width: 47.7%
                custom_fields:
                  icon_lamp: *icon_lamp
                styles: *icon_lamp_styles
                template: light

              - type: custom:button-card
                entity: light.dining_room_wall_light
                name: Matsal vägg
                style:
                  width: 47.7%
                custom_fields:
                  icon_lamp: *icon_lamp
                styles: *icon_lamp_styles
                template: light

              - type: conditional
                conditions:
                  - entity: input_boolean.julbelysning
                    state: "on"
                card:
                  type: custom:button-card
                  entity: switch.on_off_plug_in_unit_7
                  name: Adventsljusstake
                  style:
                    width: 47.7%
                  custom_fields:
                    icon_lamp: *icon_lamp
                  styles: *icon_lamp_styles
                  template: light

              - type: custom:button-card
                entity: sensor.kitchen
                name: Kök
                style:
                  width: 47.7%
                custom_fields:
                  icon_lamp: >
                    <ha-icon icon="mdi:thermometer"></ha-icon>
                styles: *icon_lamp_styles
                template: base
                tap-action:
                  action: more-info

              - type: custom:button-card
                entity: sensor.dining_room
                name: Matsal
                style:
                  width: 47.7%
                custom_fields:
                  icon_lamp: >
                    <ha-icon icon="mdi:thermometer"></ha-icon>
                styles: *icon_lamp_styles
                template: base
                tap-action:
                  action: more-info

              - type: custom:button-card
                entity: sensor.tunex_e001_temp
                name: Kylskåp
                style:
                  width: 47.7%
                custom_fields:
                  icon_lamp: >
                    <ha-icon icon="mdi:fridge"></ha-icon>
                styles: *icon_lamp_styles
                template: base
                tap-action:
                  action: more-info

          ##########################################################################
          #                                                                        #
          #                             Kontor                                     #
          #                                                                        #
          ##########################################################################
          - type: grid
            columns: 2
            title: Kontor
            cards:
              #################################################
              #                                               #
              #                   BELYSNING                   #
              #                                               #
              #################################################

              - type: custom:button-card
                entity: light.office_wall_lights
                name: Vägglampor
                style:
                  width: 47.7%
                custom_fields:
                  icon_lamp: *icon_lamp
                styles: *icon_lamp_styles
                template: light

              - type: custom:button-card
                entity: sensor.tunex_2801_temp
                name: Kontor
                style:
                  width: 47.7%
                custom_fields:
                  icon_lamp: >
                    <ha-icon icon="mdi:thermometer"></ha-icon>
                styles: *icon_lamp_styles
                template: base
                tap-action:
                  action: more-info

          ##########################################################################
          #                                                                        #
          #                             TV-rum                                     #
          #                                                                        #
          ##########################################################################
          - type: grid
            columns: 2
            title: TV-rum
            cards:
              #################################################
              #                                               #
              #                   BELYSNING                   #
              #                                               #
              #################################################

              - type: custom:button-card
                entity: light.tv_room_led_slinga
                name: LED-slinga
                style:
                  width: 47.7%
                custom_fields:
                  icon_lamp: *icon_lamp
                styles: *icon_lamp_styles
                template: light

          ##########################################################################
          #                                                                        #
          #                             Sovrum                                     #
          #                                                                        #
          ##########################################################################
          - type: grid
            columns: 2
            title: Sovrum
            cards:
              #################################################
              #                                               #
              #                   BELYSNING                   #
              #                                               #
              #################################################

              - type: custom:button-card
                entity: light.color_temperature_light_3
                name: Sänglampa Samuel
                style:
                  width: 47.7%
                custom_fields:
                  icon_lamp: *icon_lamp
                styles: *icon_lamp_styles
                template: light

              - type: conditional
                conditions:
                  - entity: input_boolean.julbelysning
                    state: "on"
                card:
                  type: custom:button-card
                  entity: light.sovrum_fonster
                  name: Stjärna i fönstret
                  style:
                    width: 47.7%
                  custom_fields:
                    icon_lamp: >
                      <ha-icon icon="mdi:hexagram-outline"></ha-icon>
                  styles: *icon_lamp_styles
                  template: light

              - type: custom:button-card
                entity: sensor.bedroom
                name: Sovrum
                style:
                  width: 47.7%
                custom_fields:
                  icon_lamp: >
                    <ha-icon icon="mdi:thermometer"></ha-icon>
                styles: *icon_lamp_styles
                template: base
                tap-action:
                  action: more-info

      - type: horizontal-stack
        cards:
          #################################################
          #                                               #
          #                RELOAD BUTTON                  #
          #                                               #
          #################################################
          - type: custom:button-card
            name: '<ha-icon icon="mdi:reload"></ha-icon> Lovelace'
            tap_action:
              action: call-service
              service: browser_mod.lovelace_reload
            template:
              name_action
              #################################################
              #                                               #
              #           INFORMATION BUTTON                  #
              #                                               #
              #################################################
          - type: custom:button-card
            name: '<ha-icon icon="mdi:information-outline"></ha-icon> Information'
            tap_action: !include popup/sidebar_information.yaml
            template:
              name_action

              #################################################
              #                                               #
              #                UPDATES BUTTON                 #
              #                                               #
              #################################################

          - type: custom:button-card
            name: '<ha-icon icon="mdi:arrow-up-bold-circle-outline"></ha-icon> Uppdateringar'
            tap_action: !include popup/sidebar_update.yaml
            template: name_action
